import type { ColumnInfo } from "@/store/useAppStore";
import type { RowDataInput } from "@/lib/db";
import { isSchemaFlagEnabled } from "./schemaFlags";

export const SAMPLE_DATA_ROWS_PER_BATCH = 200;

function isColumnAutoGenerated(column: ColumnInfo): boolean {
  const type = column.col_type.toLowerCase();
  return isSchemaFlagEnabled(column.pk) && type.includes("int");
}

function pickTextValue(columnName: string, rowNumber: number): string {
  const normalized = columnName.toLowerCase();

  if (normalized.includes("email")) {
    return `seed.user.${rowNumber}@example.com`;
  }
  if (normalized.includes("name")) {
    return `Sample ${rowNumber}`;
  }
  if (normalized.includes("title")) {
    return `Record ${rowNumber}`;
  }
  if (normalized.includes("status")) {
    return rowNumber % 3 === 0 ? "archived" : rowNumber % 2 === 0 ? "active" : "draft";
  }
  if (normalized.includes("phone")) {
    return `555-01${String(rowNumber).padStart(4, "0")}`;
  }
  if (normalized.includes("url")) {
    return `https://example.com/item/${rowNumber}`;
  }
  if (normalized.includes("city")) {
    return ["Phnom Penh", "Bangkok", "Singapore", "Tokyo"][rowNumber % 4];
  }
  if (normalized.includes("country")) {
    return ["Cambodia", "Thailand", "Singapore", "Japan"][rowNumber % 4];
  }
  if (normalized.includes("description") || normalized.includes("notes")) {
    return `Synthetic row ${rowNumber} generated by VibeDB.`;
  }

  return `${columnName}_${rowNumber}`;
}

function toSampleValue(column: ColumnInfo, rowNumber: number): unknown {
  const type = column.col_type.toLowerCase();
  const columnName = column.name.toLowerCase();

  if (type.includes("blob")) {
    return null;
  }
  if (type.includes("json")) {
    return { seed: true, row: rowNumber, column: column.name };
  }
  if (type.includes("bool")) {
    return rowNumber % 2 === 0;
  }
  if (type.includes("date") && !type.includes("time")) {
    const day = ((rowNumber - 1) % 28) + 1;
    return `2026-01-${String(day).padStart(2, "0")}`;
  }
  if (type.includes("time")) {
    const hour = rowNumber % 24;
    const minute = (rowNumber * 7) % 60;
    const second = (rowNumber * 13) % 60;
    return `2026-01-01 ${String(hour).padStart(2, "0")}:${String(minute).padStart(2, "0")}:${String(second).padStart(2, "0")}`;
  }
  if (
    type.includes("int") ||
    type.includes("real") ||
    type.includes("double") ||
    type.includes("float") ||
    type.includes("numeric") ||
    type.includes("decimal")
  ) {
    if (columnName.includes("price") || columnName.includes("amount") || columnName.includes("total")) {
      return Number((rowNumber * 3.25).toFixed(2));
    }
    if (columnName.includes("rating") || columnName.includes("score")) {
      return (rowNumber % 5) + 1;
    }
    return rowNumber;
  }

  return pickTextValue(column.name, rowNumber);
}

export function getInsertableColumns(columns: ColumnInfo[]): ColumnInfo[] {
  return columns.filter((column) => !isColumnAutoGenerated(column));
}

export function buildSampleDataRowBatch(
  columns: ColumnInfo[],
  startRowNumber: number,
  rowCount: number,
): RowDataInput[] {
  const insertableColumns = getInsertableColumns(columns);
  if (insertableColumns.length === 0) {
    throw new Error("No insertable columns found for the selected table.");
  }

  return Array.from({ length: rowCount }, (_, index) => {
    const rowNumber = startRowNumber + index;
    const rowData: Record<string, unknown> = {};
    insertableColumns.forEach((column) => {
      rowData[column.name] = toSampleValue(column, rowNumber);
    });
    return { rowData };
  });
}
