import type { ColumnInfo } from "@/store/useAppStore";

const ROWS_PER_BATCH = 200;

function escapeSqlString(value: string): string {
  return value.replace(/'/g, "''");
}

function quoteIdentifier(value: string): string {
  return `"${value.replace(/"/g, '""')}"`;
}

function toSqlString(value: string): string {
  return `'${escapeSqlString(value)}'`;
}

function isColumnAutoGenerated(column: ColumnInfo): boolean {
  const type = column.col_type.toLowerCase();
  return column.pk > 0 && type.includes("int");
}

function pickTextValue(columnName: string, rowNumber: number): string {
  const normalized = columnName.toLowerCase();

  if (normalized.includes("email")) {
    return `seed.user.${rowNumber}@example.com`;
  }
  if (normalized.includes("name")) {
    return `Sample ${rowNumber}`;
  }
  if (normalized.includes("title")) {
    return `Record ${rowNumber}`;
  }
  if (normalized.includes("status")) {
    return rowNumber % 3 === 0 ? "archived" : rowNumber % 2 === 0 ? "active" : "draft";
  }
  if (normalized.includes("phone")) {
    return `555-01${String(rowNumber).padStart(4, "0")}`;
  }
  if (normalized.includes("url")) {
    return `https://example.com/item/${rowNumber}`;
  }
  if (normalized.includes("city")) {
    return ["Phnom Penh", "Bangkok", "Singapore", "Tokyo"][rowNumber % 4];
  }
  if (normalized.includes("country")) {
    return ["Cambodia", "Thailand", "Singapore", "Japan"][rowNumber % 4];
  }
  if (normalized.includes("description") || normalized.includes("notes")) {
    return `Synthetic row ${rowNumber} generated by VibeDB.`;
  }

  return `${columnName}_${rowNumber}`;
}

function toSqlLiteral(column: ColumnInfo, rowNumber: number): string {
  const type = column.col_type.toLowerCase();
  const columnName = column.name.toLowerCase();

  if (type.includes("blob")) {
    return "NULL";
  }
  if (type.includes("json")) {
    return toSqlString(JSON.stringify({ seed: true, row: rowNumber, column: column.name }));
  }
  if (type.includes("bool")) {
    return rowNumber % 2 === 0 ? "1" : "0";
  }
  if (type.includes("date") && !type.includes("time")) {
    const day = ((rowNumber - 1) % 28) + 1;
    return toSqlString(`2026-01-${String(day).padStart(2, "0")}`);
  }
  if (type.includes("time")) {
    const hour = rowNumber % 24;
    const minute = (rowNumber * 7) % 60;
    const second = (rowNumber * 13) % 60;
    return toSqlString(
      `2026-01-01 ${String(hour).padStart(2, "0")}:${String(minute).padStart(2, "0")}:${String(second).padStart(2, "0")}`,
    );
  }
  if (
    type.includes("int") ||
    type.includes("real") ||
    type.includes("double") ||
    type.includes("float") ||
    type.includes("numeric") ||
    type.includes("decimal")
  ) {
    if (columnName.includes("price") || columnName.includes("amount") || columnName.includes("total")) {
      return (rowNumber * 3.25).toFixed(2);
    }
    if (columnName.includes("rating") || columnName.includes("score")) {
      return ((rowNumber % 5) + 1).toString();
    }
    return String(rowNumber);
  }

  return toSqlString(pickTextValue(column.name, rowNumber));
}

export function getInsertableColumns(columns: ColumnInfo[]): ColumnInfo[] {
  return columns.filter((column) => !isColumnAutoGenerated(column));
}

export function buildSampleDataTransaction(
  tableName: string,
  columns: ColumnInfo[],
  rowCount: number,
): string[] {
  const insertableColumns = getInsertableColumns(columns);
  if (insertableColumns.length === 0) {
    throw new Error("No insertable columns found for the selected table.");
  }

  const quotedTableName = quoteIdentifier(tableName);
  const quotedColumns = insertableColumns.map((column) => quoteIdentifier(column.name)).join(", ");
  const queries: string[] = [];

  for (let start = 0; start < rowCount; start += ROWS_PER_BATCH) {
    const batchSize = Math.min(ROWS_PER_BATCH, rowCount - start);
    const values = Array.from({ length: batchSize }, (_, index) => {
      const rowNumber = start + index + 1;
      const rowValues = insertableColumns.map((column) => toSqlLiteral(column, rowNumber)).join(", ");
      return `(${rowValues})`;
    });

    queries.push(`INSERT INTO ${quotedTableName} (${quotedColumns}) VALUES\n${values.join(",\n")};`);
  }

  return queries;
}
