import type { ColumnInfo } from "@/store/useAppStore";

export const quoteIdentifier = (identifier: string): string =>
  `"${identifier.replace(/"/g, '""')}"`;

export const escapeSqlString = (value: string): string =>
  value.replace(/'/g, "''");

export const isNumericColumn = (columnType: string): boolean => {
  const type = columnType.toLowerCase();
  return (
    type.includes("int") ||
    type.includes("real") ||
    type.includes("double") ||
    type.includes("float") ||
    type.includes("numeric") ||
    type.includes("decimal")
  );
};

export const isAutoGeneratedPkColumn = (column: ColumnInfo): boolean =>
  Boolean(column.pk) && column.col_type.toLowerCase().includes("int");

export const formatSqlValue = (
  value: string,
  columnInfo?: ColumnInfo,
): string => {
  if (value === "" || value === "NULL") {
    return "NULL";
  }

  if (columnInfo && isNumericColumn(columnInfo.col_type)) {
    if (Number.isNaN(Number(value))) {
      throw new Error("Please enter a valid number");
    }
    return value;
  }

  return `'${escapeSqlString(value)}'`;
};
