import type { ColumnInfo } from "@/store/useAppStore";

export const isNumericColumn = (columnType: string): boolean => {
  const type = columnType.toLowerCase();
  return (
    type.includes("int") ||
    type.includes("real") ||
    type.includes("double") ||
    type.includes("float") ||
    type.includes("numeric") ||
    type.includes("decimal")
  );
};

export const isJsonColumn = (columnType: string): boolean =>
  columnType.toLowerCase().includes("json");

export const isBooleanColumn = (columnType: string): boolean => {
  const type = columnType.toLowerCase();
  return type.includes("bool");
};

export const isAutoGeneratedPkColumn = (column: ColumnInfo): boolean =>
  Boolean(column.pk) && column.col_type.toLowerCase().includes("int");
