export const MAX_RESULT_ROWS = 1000;
export const MAX_TABS = 20;
export const MAX_ACTIVE_CONNECTIONS = 5;
export const MAX_QUICK_SEARCH_RECENT_ITEMS = 12;
export const DEFAULT_TABLE_PAGE_SIZE = 100;
export const MAX_SAVED_QUERIES = 500;
export const MAX_SAVED_QUERY_NAME_LENGTH = 100;
export const MAX_SAVED_QUERY_SQL_LENGTH = 100000;
