import { useState, useRef } from "react";
import { executeQuery } from "@/lib/db";
import { useAppStore } from "@/store/useAppStore";
import type { ColumnInfo } from "@/store/useAppStore";
import {
  escapeSqlString,
  isAutoGeneratedPkColumn,
  isNumericColumn,
  quoteIdentifier,
} from "@/lib/sql-helpers";

export const useNewRow = (
  tableName: string,
  structure: ColumnInfo[],
  activeConnection: { connId?: string } | null | undefined,
  fetchData: () => Promise<void>,
) => {
  const [newRowData, setNewRowData] = useState<Record<string, string> | null>(
    null,
  );
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState("");
  const newRowDataRef = useRef(newRowData);
  newRowDataRef.current = newRowData;

  const handleAddRow = () => {
    const initialData: Record<string, string> = {};
    structure.forEach((col) => {
      if (isAutoGeneratedPkColumn(col)) {
        return;
      }
      if (col.dflt_value) {
        initialData[col.name] = "DEFAULT";
      }
    });
    setNewRowData(initialData);
  };

  const handleDiscardNewRow = () => {
    setNewRowData(null);
    setError("");
  };

  const buildInsertSql = (rowData: Record<string, string>) => {
    const entries = Object.entries(rowData).filter(([k, v]) => {
      if (v === "" || v === "DEFAULT") return false;
      const col = structure.find((c) => c.name === k);
      if (!col) return false;
      if (isAutoGeneratedPkColumn(col)) return false;
      return true;
    });

    if (entries.length === 0) {
      const hasDefaults = Object.values(rowData).some((v) => v === "DEFAULT");
      if (hasDefaults) {
        return `INSERT INTO ${quoteIdentifier(tableName)} DEFAULT VALUES;`;
      }
      throw new Error("Please enter at least one value");
    }

    const colNames = entries.map(([k]) => quoteIdentifier(k)).join(", ");
    const placeholders = entries
      .map(([k, v]) => {
        if (v === "NULL") return "NULL";
        const col = structure.find((c) => c.name === k);
        const type = col?.col_type.toLowerCase() || "";
        if (isNumericColumn(type)) {
          if (Number.isNaN(Number(v))) {
            throw new Error(`Invalid numeric value for "${k}"`);
          }
          return v;
        }
        return `'${escapeSqlString(v)}'`;
      })
      .join(", ");

    return `INSERT INTO ${quoteIdentifier(tableName)} (${colNames}) VALUES (${placeholders});`;
  };

  const getPendingInsertQuery = () => {
    if (!newRowData) return null;
    return buildInsertSql(newRowData);
  };

  const handleSaveNewRow = async () => {
    if (!activeConnection?.connId || !newRowData) return;
    setSaving(true);
    setError("");
    const startTime = performance.now();

    try {
      const sql = buildInsertSql(newRowData);

      await executeQuery(sql, activeConnection.connId);

      const duration = performance.now() - startTime;
      useAppStore.getState().addLog({
        sql,
        status: "success",
        duration,
        message: "Row inserted successfully",
      });

      setNewRowData(null);
      await fetchData();
    } catch (e: any) {
      const duration = performance.now() - startTime;
      setError(e.toString());
      useAppStore.getState().addLog({
        sql: `INSERT INTO "${tableName}" ...`,
        status: "error",
        duration,
        message: e.toString(),
      });
    } finally {
      setSaving(false);
    }
  };

  return {
    newRowData,
    setNewRowData,
    newRowDataRef,
    saving,
    error,
    setError,
    handleAddRow,
    handleDiscardNewRow,
    handleSaveNewRow,
    getPendingInsertQuery,
  };
};
