import { useMemo, useRef, useState } from "react";
import { insertRows, type RowDataInput } from "@/lib/db";
import { isAutoGeneratedPkColumn } from "@/lib/sql/columnTypes";
import { parseStructuredColumnValue } from "@/lib/sql/values";
import type { ColumnInfo } from "@/store/useAppStore";

export const useNewRow = (
  tableName: string,
  structure: ColumnInfo[],
  activeConnection: { connId?: string } | null | undefined,
  fetchData: () => Promise<void>,
) => {
  const [newRowData, setNewRowData] = useState<Record<string, string> | null>(
    null,
  );
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState("");
  const newRowDataRef = useRef(newRowData);
  newRowDataRef.current = newRowData;
  const columnInfoByName = useMemo(() => {
    const map: Record<string, ColumnInfo> = {};
    structure.forEach((column) => {
      map[column.name] = column;
    });
    return map;
  }, [structure]);

  const handleAddRow = () => {
    const initialData: Record<string, string> = {};
    structure.forEach((col) => {
      if (isAutoGeneratedPkColumn(col)) {
        return;
      }
      if (col.dflt_value) {
        initialData[col.name] = "DEFAULT";
      }
    });
    setNewRowData(initialData);
  };

  const handleDiscardNewRow = () => {
    setNewRowData(null);
    setError("");
  };

  // Build RowDataInput for backend SQL generation
  const buildRowDataInput = (rowData: Record<string, string>): RowDataInput => {
    const rowDataMap: Record<string, unknown> = {};

    for (const [key, value] of Object.entries(rowData)) {
      if (value === "DEFAULT") continue;

      const col = columnInfoByName[key];
      if (!col) continue;
      if (isAutoGeneratedPkColumn(col)) continue;

      const parsedValue = parseStructuredColumnValue(value, col, {
        emptyStringBehavior: "omit",
      });
      if (parsedValue !== undefined) {
        rowDataMap[key] = parsedValue;
      }
    }

    return { rowData: rowDataMap };
  };

  const validateRowData = (rowData: Record<string, string>): string | null => {
    try {
      const rowInput = buildRowDataInput(rowData);
      const hasValue = Object.keys(rowInput.rowData).length > 0;

      if (!hasValue) {
        const hasDefaults = Object.values(rowData).some((v) => v === "DEFAULT");
        if (!hasDefaults) {
          return "Please enter at least one value";
        }
      }

      return null;
    } catch (error: unknown) {
      return error instanceof Error ? error.message : String(error);
    }
  };

  const handleSaveNewRow = async (): Promise<boolean> => {
    if (!activeConnection?.connId || !newRowData) return false;
    setSaving(true);
    setError("");

    try {
      const validationError = validateRowData(newRowData);
      if (validationError) {
        throw new Error(validationError);
      }

      const rowInput = buildRowDataInput(newRowData);
      await insertRows(tableName, [rowInput], activeConnection.connId);

      setNewRowData(null);
      await fetchData();
      return true;
    } catch (e: any) {
      setError(e.toString());
      return false;
    } finally {
      setSaving(false);
    }
  };

  return {
    newRowData,
    setNewRowData,
    newRowDataRef,
    saving,
    error,
    setError,
    handleAddRow,
    handleDiscardNewRow,
    handleSaveNewRow,
  };
};
