import { useEffect, useState } from 'react';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Checkbox } from '@/components/ui/checkbox';

interface ImportConfirmDialogProps {
  open: boolean;
  tableName: string;
  fileName: string;
  autoGeneratedColumns: string[];
  pending: boolean;
  onOpenChange: (open: boolean) => void;
  onConfirm: (excludeAutoGeneratedColumns: boolean) => void;
}

export function ImportConfirmDialog({
  open,
  tableName,
  fileName,
  autoGeneratedColumns,
  pending,
  onOpenChange,
  onConfirm,
}: ImportConfirmDialogProps) {
  const hasAutoGeneratedColumns = autoGeneratedColumns.length > 0;
  const [excludeAutoGeneratedColumns, setExcludeAutoGeneratedColumns] = useState(false);

  useEffect(() => {
    if (!open) {
      return;
    }

    setExcludeAutoGeneratedColumns(false);
  }, [open]);

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[460px]">
        <DialogHeader>
          <DialogTitle>Confirm Import</DialogTitle>
          <DialogDescription>
            Import <span className="font-medium text-foreground">{fileName}</span> into{' '}
            <span className="font-medium text-foreground">{tableName}</span>? This appends rows and
            runs as one transaction. Constraint or validation errors will fail the full import.
          </DialogDescription>
        </DialogHeader>

        {hasAutoGeneratedColumns && (
          <label className="flex items-start gap-3 rounded-lg border border-border bg-secondary/40 p-3">
            <Checkbox
              checked={excludeAutoGeneratedColumns}
              onCheckedChange={(checked) => setExcludeAutoGeneratedColumns(checked === true)}
              aria-label="Exclude auto-generated ID columns"
              className="mt-0.5"
            />
            <div className="space-y-1">
              <div className="text-sm font-medium text-foreground">
                Exclude auto-generated ID columns
              </div>
              <div className="text-xs text-muted-foreground">
                Skip {autoGeneratedColumns.join(', ')} so the database can generate fresh values
                during append-style imports.
              </div>
            </div>
          </label>
        )}

        <DialogFooter>
          <Button variant="outline" onClick={() => onOpenChange(false)} disabled={pending}>
            Cancel
          </Button>
          <Button onClick={() => onConfirm(excludeAutoGeneratedColumns)} disabled={pending}>
            {pending ? 'Importing...' : 'Import Rows'}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
