import { useCallback, useState } from 'react';
import { useAppStore, type Connection } from '@/store/useAppStore';
import { exportTableData, getTableStructure, importTableData } from '@/lib/db';
import { isAutoGeneratedPkColumn } from '@/lib/sql/columnTypes';
import { TABLE_TRANSFER_IMPORTED_EVENT } from './constants';
import { pickExportPath, pickImportPath } from './dialogs';
import { resolveTableTransferContext } from './state';
import type { TableTransferFormat, TableTransferImportedDetail } from './types';

type ImportFormat = Exclude<TableTransferFormat, 'sql'>;

interface PendingImportState {
  tableName: string;
  format: ImportFormat;
  sourcePath: string;
  fileName: string;
  autoGeneratedColumns: string[];
}

function getErrorMessage(error: unknown): string {
  if (error instanceof Error) {
    return error.message;
  }
  return String(error);
}

function getFileName(path: string): string {
  const segments = path.split(/[/\\]/);
  return segments[segments.length - 1] || path;
}

export function useTableTransfer(connection?: Connection) {
  const showToast = useAppStore((state) => state.showToast);
  const [isTransferPending, setIsTransferPending] = useState(false);
  const [pendingImport, setPendingImport] = useState<PendingImportState | null>(null);

  const exportTable = useCallback(
    async (tableName: string, format: TableTransferFormat) => {
      if (!connection?.connId || isTransferPending) {
        return;
      }

      const destinationPath = await pickExportPath(tableName, format);
      if (!destinationPath) {
        return;
      }

      setIsTransferPending(true);
      try {
        const context = resolveTableTransferContext(
          useAppStore.getState(),
          connection.id,
          tableName,
        );
        const result = await exportTableData(
          {
            tableName,
            format,
            destinationPath,
            filters: context.filters,
            sortCol: context.sortCol,
            sortDir: context.sortDir,
          },
          connection.connId,
        );
        showToast({ type: 'success', message: result.message });
      } catch (error) {
        showToast({
          type: 'error',
          message: `Export failed: ${getErrorMessage(error)}`,
        });
      } finally {
        setIsTransferPending(false);
      }
    },
    [connection, isTransferPending, showToast],
  );

  const importTable = useCallback(
    async (tableName: string, format: ImportFormat) => {
      if (!connection?.connId || isTransferPending) {
        return;
      }

      const sourcePath = await pickImportPath(format);
      if (!sourcePath) {
        return;
      }

      const fileName = getFileName(sourcePath);
      try {
        const structure = await getTableStructure(tableName, connection.connId);
        setPendingImport({
          tableName,
          format,
          sourcePath,
          fileName,
          autoGeneratedColumns: structure.columns
            .filter(isAutoGeneratedPkColumn)
            .map((column) => column.name),
        });
      } catch (error) {
        showToast({
          type: 'error',
          message: `Import setup failed: ${getErrorMessage(error)}`,
        });
      }
    },
    [connection, isTransferPending, showToast],
  );

  const confirmImport = useCallback(
    async (excludeAutoGeneratedColumns: boolean) => {
      if (!connection?.connId || !pendingImport || isTransferPending) {
        return;
      }

      setIsTransferPending(true);
      try {
        const result = await importTableData(
          {
            tableName: pendingImport.tableName,
            format: pendingImport.format,
            sourcePath: pendingImport.sourcePath,
            excludeColumns: excludeAutoGeneratedColumns
              ? pendingImport.autoGeneratedColumns
              : [],
          },
          connection.connId,
        );
        showToast({ type: 'success', message: result.message });
        window.dispatchEvent(
          new CustomEvent<TableTransferImportedDetail>(TABLE_TRANSFER_IMPORTED_EVENT, {
            detail: {
              connectionId: connection.id,
              tableName: pendingImport.tableName,
            },
          }),
        );
        setPendingImport(null);
      } catch (error) {
        showToast({
          type: 'error',
          message: `Import failed: ${getErrorMessage(error)}`,
        });
      } finally {
        setIsTransferPending(false);
      }
    },
    [connection, isTransferPending, pendingImport, showToast],
  );

  const closeImportDialog = useCallback((open: boolean) => {
    if (!open) {
      setPendingImport(null);
    }
  }, []);

  return {
    exportTable,
    importTable,
    confirmImport,
    closeImportDialog,
    isTransferPending,
    pendingImport,
  };
}
